set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s escape-time 0
set -g mouse on
set -g base-index 1

# Leader
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r m resize-pane -Z

bind M-c attach-session -c "#{pane_current_path}"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# CONFIGS
# Window settings
#setw -g window-active-style bg=colour232   # Set the background color of the active window
#setw -g window-style bg=colour52   # Set the background color of inactive windows

# AUTO COLOR CONFIG
tmux_conf_24b_colour=auto

# new window retains current path, possible values are: (true, false, disabled)
tmux_conf_new_window_retain_current_path=false

# new pane retains current path, possible values are: (true, false, disabled)
tmux_conf_new_pane_retain_current_path=true

# clipboard 
# in copy mode, copying selection also copies to the OS clipboard: (true, false, disabled)
# on Linux, this requires xsel, xclip or wl-copy
tmux_conf_copy_to_os_clipboard=true

